### ISSUE TITLE
Django auth UserCreationForm form not working as expected

### ISSUE THREAD

**Issue by KevinHamonApp** [jmfederico/django-use-email-as-username#15] opened 2024-02-05 16:27 UTC
* Django use Email as Username version: 1.4.0
* Django version: 5
* Python version: 3.11
* Operating System: Ubuntu

### Description

First, thanks a lot for the job. I used the package multiple times in DRF API projects with dj-rest-auth authentication, and it works very well ! 

I'm today using Django generic views. 
I installed the package as described on the project, all works for admin creation / update of users, login etc. 
I tried using Login view `django.contrib.auth.views.LoginView`, which uses by default `django.contrib.auth.forms.AuthenticationForm`. All works as expected, with email and password fields. Amazing !

I then tried to set a SignUpview, using `django.contrib.auth.forms.UserCreationForm`. However, the form shows a username field, and after submit of the form, I got an error.

Is there any way to make a UserCreationForm that works just as the AuthenticationForm with email, that is already planned ? Or shall we develop it ?

### What I did
**My view**
```
class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("login")
```

**My template (using bootstrap)**
```
{% bootstrap_form_errors form layout='inline' %}

<form method="post">
  {% csrf_token %} {% bootstrap_form form %}
  <!-- prettier-ignore -->
  {% bootstrap_button "Valider" button_type="submit" button_class="btn-primary" %}
</form>

<p>
  Déjà un compte ?
  <a href="{% url 'login' %}">Se connecter</a>
</p>
```

**View rendered**
![image](https://github.com/jmfederico/django-use-email-as-username/assets/74555017/d3627b51-a57b-42f3-9d93-13ed51db2c5d)

**Submit output** 
``
Manager isn't available; 'auth.User' has been swapped for 'authentication.User'
``

**Comment by jmfederico** [comment] 2024-02-06 04:44
The error message you get is telling you that you are using the wrong `User` model.

This is happening because `django.contrib.auth.forms.UserCreationForm` uses the `User` model from `django.contrib.auth.models` which is not your model any more.
See here https://github.com/django/django/blob/9cefdfc43f0bae696b56fa5a0bf22346f85affff/django/contrib/auth/forms.py#L115

You would need to create your own form.
This could probably be done by subclassing it and overriding the `model` property on `Meta`, and set it to your own `User` model. I have not tested this solution myself.

I am closing this issue, as it is not a bug with this module.

**Closed as completed by jmfederico** 2024-02-06 04:44 UTC

**Comment by KevinHamonApp** [comment] 2024-02-14 16:51
Thanks for quick answer ! @jmfederico 

Indeed, creating my own form works. Here is my implementation for those who would need it : 
```python
from django.contrib.auth.forms import (
    BaseUserCreationForm,
)

from .models import User


class CustomUserCreationForm(BaseUserCreationForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
```

What surprised me, is that Login worked out of the box with the package, and not UserCreation. After making some researches, I discovered that login worked, but the input is still an input of type `text`. I think this is not really what we expect.

I added a forms.py file : 
```python
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from django.forms import EmailField
from django.contrib.admin.forms import AdminAuthenticationForm
from django.utils.translation import gettext_lazy as _

class CustomAdminAuthenticationForm(AdminAuthenticationForm):
    username = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", "autofocus": True}),
    )

class CustomAuthenticationForm(AuthenticationForm):
    username = EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", "autofocus": True}),
    )
```

This form can be registered in a login view, but also in admin to login : 
```python
from django.contrib import admin
from .forms import CustomAdminAuthenticationForm


class MyAdminSite(admin.AdminSite):
    login_form = CustomAdminAuthenticationForm


admin_site = MyAdminSite(name="admin")

```

This way we have the right login form, with an email type input.

I think this is basic setup of an app using this package. I would find it useful if mentionned in the example project of the repo. What do you think ?
